In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

pd.set_option("display.max_columns",100)
pd.set_option("display.max_rows",100)

In [12]:
df=pd.read_excel("World military power.xlsx",header=1)

In [14]:
df.sample(5)

,Military Strength,Military Strength Power Index,Aircraft Strength,Aircraft Strength value,Fighter/Interceptor Strength,Fighter/Interceptor Strength value,Attack Aircraft Strength,Attack Aircraft Strength value,Transport Aircraft Fleet Strength,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet,Trainer Aircraft Fleet value,Helicopter Fleet Strength,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength,Attack Helicopter Fleet Strength value,Tank Strength,Tank Strength value,AFV/APC Strength,AFV/APC Strength value,Self-Propelled Artillery Strength,Self-Propelled Artillery Strength value,Towed Artillery Strength,Towed Artillery Strength value,Rocket Projector Strength,Rocket Projector Strength value,Navy Fleet Strengths,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength,Submarine Fleet Strength value,Destroyer Fleet Strength,Destroyer Fleet Strength value,Frigate Fleet Strength,Frigate Fleet Strength value,defense spending budget,defense spending budget value,External Debt,External Debt value,Airport Totals,Airport Totals value,Oil Production,Oil Production value,Oil Consumption,Oil Consumption value,Proven Oil Reserves,Proven Oil Reserves value,Available Manpower,Available Manpower value,Total Population,Total Population value,Total Square Land Area,Total Square Land Area value,Total Coastline Coverage,Total Coastline Coverage value,Total Waterway Coverage,Total Waterway Coverage value,Total Border Coverage,Total Border Coverage value
116,Sweden,0.5304,Sweden,204.0,Sweden,71.0,Sweden,0.0,Sweden,6.0,Sweden,69.0,Sweden,53.0,Sweden,0.0,Sweden,126.0,Sweden,1036.0,Sweden,88.0,Sweden,0.0,Sweden,0.0,Sweden,63.0,Sweden,0.0,Sweden,5.0,Sweden,0.0,Sweden,0.0,Sweden,"6,32,69,23,600",Sweden,"9,39,90,00,00,000",Sweden,231.0,Sweden,0.0,Sweden,"3,20,000",Sweden,0.0,Sweden,"41,16,808",Sweden,"1,00,40,995",Sweden,"4,50,295",Sweden,3218.0,Sweden,2052.0,Sweden,2211.0
49,India,0.0953,India,2123.0,India,538.0,India,172.0,India,250.0,India,359.0,India,722.0,India,23.0,India,4292.0,India,8686.0,India,235.0,India,4060.0,India,266.0,India,285.0,India,1.0,India,16.0,India,10.0,India,13.0,India,"61,00,00,00,000",India,"5,01,60,00,00,000",India,346.0,India,"7,33,900",India,"50,00,000",India,"4,62,10,00,000",India,"62,24,80,340",India,"1,29,68,34,042",India,"32,87,263",India,7000.0,India,14500.0,India,13888.0
129,United Kingdom,0.1717,United Kingdom,733.0,United Kingdom,133.0,United Kingdom,15.0,United Kingdom,44.0,United Kingdom,241.0,United Kingdom,312.0,United Kingdom,49.0,United Kingdom,227.0,United Kingdom,5000.0,United Kingdom,89.0,United Kingdom,126.0,United Kingdom,35.0,United Kingdom,88.0,United Kingdom,2.0,United Kingdom,10.0,United Kingdom,6.0,United Kingdom,13.0,United Kingdom,"55,10,00,00,000",United Kingdom,"81,26,00,00,00,000",United Kingdom,460.0,United Kingdom,"9,10,500",United Kingdom,"16,00,000",United Kingdom,"2,56,40,00,000",United Kingdom,"2,99,48,413",United Kingdom,"6,51,05,246",United Kingdom,"2,43,610",United Kingdom,12429.0,United Kingdom,3200.0,United Kingdom,443.0
35,Egypt,0.1872,Egypt,1054.0,Egypt,215.0,Egypt,88.0,Egypt,59.0,Egypt,387.0,Egypt,294.0,Egypt,81.0,Egypt,4295.0,Egypt,11700.0,Egypt,1139.0,Egypt,2189.0,Egypt,1084.0,Egypt,316.0,Egypt,2.0,Egypt,8.0,Egypt,0.0,Egypt,7.0,Egypt,"11,20,00,00,000",Egypt,"77,47,00,00,000",Egypt,83.0,Egypt,"5,89,400",Egypt,"8,32,000",Egypt,"4,40,00,00,000",Egypt,"4,29,46,553",Egypt,"9,94,13,317",Egypt,"10,01,450",Egypt,2450.0,Egypt,3500.0,Egypt,2612.0
78,Mozambique,2.3364,Mozambique,16.0,Mozambique,8.0,Mozambique,0.0,Mozambique,1.0,Mozambique,1.0,Mozambique,6.0,Mozambique,2.0,Mozambique,100.0,Mozambique,335.0,Mozambique,0.0,Mozambique,260.0,Mozambique,12.0,Mozambique,8.0,Mozambique,0.0,Mozambique,0.0,Mozambique,0.0,Mozambique,0.0,Mozambique,"24,50,00,000",Mozambique,"10,91,00,00,000",Mozambique,98.0,Mozambique,0.0,Mozambique,22500.0,Mozambique,0.0,Mozambique,"46,29,744",Mozambique,"2,72,33,789",Mozambique,"7,99,380",Mozambique,2470.0,Mozambique,460.0,Mozambique,4783.0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 60 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Military Strength                        138 non-null    object
 1   Military Strength Power Index            138 non-null    float64
 2   Aircraft Strength                        138 non-null    object
 3   Aircraft Strength value                  138 non-null    float64
 4   Fighter/Interceptor Strength             138 non-null    object
 5   Fighter/Interceptor Strength value       138 non-null    float64
 6   Attack Aircraft Strength                 138 non-null    object
 7   Attack Aircraft Strength value           138 non-null    float64
 8   Transport Aircraft Fleet Strength        138 non-null    object
 9   Transport Aircraft Fleet Strength value  138 non-null    float64
 10  Trainer Aircraft Fleet                   138 non-null    object
 11  Trainer Aircraft Fleet value             138 non-null    float64
 12  Helicopter Fleet Strength                138 non-null    object
 13  Helicopter Fleet Strength value          138 non-null    float64
 14  Attack Helicopter Fleet Strength         138 non-null    object
 15  Attack Helicopter Fleet Strength value   138 non-null    float64
 16  Tank Strength                            138 non-null    object
 17  Tank Strength value                      138 non-null    float64
 18  AFV/APC Strength                         138 non-null    object
 19  AFV/APC Strength value                   138 non-null    float64
 20  Self-Propelled Artillery Strength        138 non-null    object
 21  Self-Propelled Artillery Strength value  138 non-null    float64
 22  Towed Artillery Strength                 138 non-null    object
 23  Towed Artillery Strength value           138 non-null    float64
 24  Rocket Projector Strength                138 non-null    object
 25  Rocket Projector Strength value          138 non-null    float64
 26  Navy Fleet Strengths                     124 non-null    object
 27  Navy Fleet Strengths value               124 non-null    float64
 28  Aircraft Carrier Fleet Strength          115 non-null    object
 29  Aircraft Carrier Fleet Strength value    115 non-null    float64
 30  Submarine Fleet Strength                 115 non-null    object
 31  Submarine Fleet Strength value           115 non-null    float64
 32  Destroyer Fleet Strength                 115 non-null    object
 33  Destroyer Fleet Strength value           115 non-null    float64
 34  Frigate Fleet Strength                   115 non-null    object
 35  Frigate Fleet Strength value             115 non-null    float64
 36  defense spending budget                  138 non-null    object
 37  defense spending budget value            138 non-null    object
 38  External Debt                            138 non-null    object
 39  External Debt value                      138 non-null    object
 40  Airport Totals                           138 non-null    object
 41  Airport Totals value                     138 non-null    float64
 42  Oil Production                           138 non-null    object
 43  Oil Production value                     138 non-null    object
 44  Oil Consumption                          138 non-null    object
 45  Oil Consumption value                    138 non-null    object
 46  Proven Oil Reserves                      138 non-null    object
 47  Proven Oil Reserves value                138 non-null    object
 48  Available Manpower                       138 non-null    object
 49  Available Manpower value                 138 non-null    object
 50  Total Population                         138 non-null    object
 51  Total Population value                   138 non-null    object
 52  Total Square Land Area                   138 non-null    object
 53  Total Square Land Area value             138 non-null    object
 54  Total Coastline Coverage                 109 non-null    object
 55  Total Coastline Coverage value           109 non-null    object
 56  Total Waterway Coverage                  138 non-null    object
 57  Total Waterway Coverage value            138 non-null    object
 58  Total Border Coverage                    129 non-null    object
 59  Total Border Coverage value              129 non-null    float64
dtypes: float64(20), object(40)
memory usage: 64.8+ KB

In [16]:
df.isnull().sum()

Military Strength                           0
Military Strength Power Index               0
Aircraft Strength                           0
Aircraft Strength value                     0
Fighter/Interceptor Strength                0
Fighter/Interceptor Strength value          0
Attack Aircraft Strength                    0
Attack Aircraft Strength value              0
Transport Aircraft Fleet Strength           0
Transport Aircraft Fleet Strength value     0
Trainer Aircraft Fleet                      0
Trainer Aircraft Fleet value                0
Helicopter Fleet Strength                   0
Helicopter Fleet Strength value             0
Attack Helicopter Fleet Strength            0
Attack Helicopter Fleet Strength value      0
Tank Strength                               0
Tank Strength value                         0
AFV/APC Strength                            0
AFV/APC Strength value                      0
Self-Propelled Artillery Strength           0
Self-Propelled Artillery Strength value     0
Towed Artillery Strength                    0
Towed Artillery Strength value              0
Rocket Projector Strength                   0
Rocket Projector Strength value             0
Navy Fleet Strengths                       14
Navy Fleet Strengths value                 14
Aircraft Carrier Fleet Strength            23
Aircraft Carrier Fleet Strength value      23
Submarine Fleet Strength                   23
Submarine Fleet Strength value             23
Destroyer Fleet Strength                   23
Destroyer Fleet Strength value             23
Frigate Fleet Strength                     23
Frigate Fleet Strength value               23
defense spending budget                     0
defense spending budget value               0
External Debt                               0
External Debt value                         0
Airport Totals                              0
Airport Totals value                        0
Oil Production                              0
Oil Production value                        0
Oil Consumption                             0
Oil Consumption value                       0
Proven Oil Reserves                         0
Proven Oil Reserves value                   0
Available Manpower                          0
Available Manpower value                    0
Total Population                            0
Total Population value                      0
Total Square Land Area                      0
Total Square Land Area value                0
Total Coastline Coverage                   29
Total Coastline Coverage value             29
Total Waterway Coverage                     0
Total Waterway Coverage value               0
Total Border Coverage                       9
Total Border Coverage value                 9
dtype: int64

In [17]:
df.describe()

,Military Strength Power Index,Aircraft Strength value,Fighter/Interceptor Strength value,Attack Aircraft Strength value,Transport Aircraft Fleet Strength value,Trainer Aircraft Fleet value,Helicopter Fleet Strength value,Attack Helicopter Fleet Strength value,Tank Strength value,AFV/APC Strength value,Self-Propelled Artillery Strength value,Towed Artillery Strength value,Rocket Projector Strength value,Navy Fleet Strengths value,Aircraft Carrier Fleet Strength value,Submarine Fleet Strength value,Destroyer Fleet Strength value,Frigate Fleet Strength value,Airport Totals value,Total Border Coverage value
count,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,124.000000,115.000000,115.000000,115.000000,115.000000,138.000000,129.000000
mean,1.460716,388.471014,81.565217,25.760870,30.231884,82.833333,154.065217,25.623188,646.565217,2485.695652,212.159420,393.978261,156.934783,84.983871,0.382609,4.800000,2.052174,3.521739,290.043478,3964.224806
std,1.324018,1231.981859,230.324777,94.528222,92.330436,240.803721,520.183631,97.326091,1515.463683,5410.546392,688.028987,805.781703,484.380984,146.114165,1.971653,13.706958,10.000740,6.481211,1212.967393,3760.099671
min,0.060600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,29.000000
25%,0.574800,33.000000,0.000000,0.000000,3.000000,4.250000,15.250000,0.000000,19.250000,250.250000,0.000000,24.250000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,33.500000,1587.000000
50%,1.034100,111.000000,17.000000,0.000000,9.000000,26.000000,44.000000,2.000000,153.000000,734.500000,23.000000,108.000000,24.000000,38.000000,0.000000,0.000000,0.000000,0.000000,68.000000,2816.000000
75%,2.021525,290.250000,60.500000,15.750000,26.000000,79.250000,126.750000,17.750000,436.250000,2000.000000,97.250000,296.500000,99.750000,77.750000,0.000000,4.000000,0.000000,5.500000,150.750000,5267.000000
max,10.168100,13264.000000,2085.000000,742.000000,945.000000,2643.000000,5768.000000,967.000000,12950.000000,39253.000000,6083.000000,4465.000000,3860.000000,984.000000,20.000000,83.000000,91.000000,52.000000,13513.000000,22457.000000